### PR TITLE
Format code after google's java styleguide, also add codeclimate

### PR DESCRIPTION
**Pull request by JohnnyQQQQ**
**What does this PR do?**

- Major code formatting after [google's java styleguide](https://google.github.io/styleguide/javaguide.html)
- Lint tasks that checks if the code is like defined in the styleguide
- Codeclimate integration for indepth checks of the code quality

**Why are these changes required?**

If we don't use any styleguide for coding, the project might end in a big mess 😄 

**This PR has been tested by:**
- Unit Tests
- Manual Testing

**Follow up**

- A Projectmember has to setup the project on https://www.codeclimate.com
- Discuss in #48 what else we could do to improve the projects quality

**Extra details**

[Stylefile for Intellij](https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml)

[Stylefile for Eclipse](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml) Thanks @artinpetrossian

### CODE REVIEW

**Comment by artinpetrossian** [comment]
Also the stylefile for Eclipse: https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml

**Comment by suiginsoft** [comment]
I think it's also worth stating that these changes are required so that we can advertise to investors and users of the software that we meet a certain level of software quality and security. That Java-Tron, from a technical standpoint, isn't just yet another cryptocurrency protocol but rather one that takes itself seriously.

**Comment by sasaxie** [comment]
@JohnnyQQQQ conflicts

**Comment by JohnnyQQQQ** [comment]
@sasaxie resolved

**Comment by sasaxie** [comment]
@JohnnyQQQQ thanks

**Comment by ybhgenius** [comment]
Hello, I am a crew member of TRON, and now we are planning to provide an incentive for your contribution. Please leave me your email address. Thanks.

**Pull request merged**
