### PR TITLE
optimize the start shell

### PR DESCRIPTION
**Pull request by forfreeday**
1.quickstart.sh

modify:
1.optimize the start.sh
2.modify quickstart.md on quickstart.sh Instructions for use

**What does this PR do?**

**Why are these changes required?**

**This PR has been tested by:**
- Unit Tests
- Manual Testing

**Follow up**

**Extra details**

### CODE REVIEW

**Comment by Ufakeimdope** [comment]
We need my accounts activated under my tags it's been annoying trying to
figure this out knowing u have money I can't get too

**Comment by Mita1w** [comment]
Yeah I lnowthatsallny money

**Comment by Mita1w** [comment]
Your tags ur not taking accts

**Comment by WAT251922ty** [comment]
User. ***@***.***
Pass. WAT251922s$
Im. Noting. A. Withdrawal
You. Help. Mee. Pliesses
Thank. You
Khunanon. Wongouan


ในวันที่ อ. 31 ส.ค. 2021 13:51 Kayle ***@***.***> เขียนว่า:

**Review by lvs007 — APPROVED** [review]

**Pull request merged**
