### PR TITLE
Reformat code to Google java styleguide

### PR DESCRIPTION
**Pull request by jromero**
**What does this PR do?**
* Reformat code to adhere to the pre-approved notion to use the google java styleguide. See https://github.com/tronprotocol/java-tron/pull/60
* Protobuf generated classes are excluded from checkstyle
* Run `lint` as part of the `test` step
* Checks are set to warning except for `Indentation` which have been fixed in this PR

**Why are these changes required?**
* Code consistency

**This PR has been tested by:**
- Unit Tests
- Manual Testing

**Follow up**
The thought is to follow this PR up with fixes to the current lint violations and changing them from WARNING to ERROR to prevent future deviation.

**Extra details**

### CODE REVIEW

**Comment by Rovak** [comment]
You should add a travis-ci script that checks if new code complies with the styleguide. I've seen recent commits from other developers that violate the code guidelines.

**Comment by jromero** [comment]
@Rovak Good idea. 

I went ahead and elevated the warnings to errors and made `test` depend on `lint`. 

One thing I must note is that there are A LOT of violations. I suppressed some locally via annotations and others globally by commenting out the rule in the `google_checks.xml`. Without doing that I would think this PR would be extremely large. This allows those disabled rules to be tackled as independent PRs.

**Comment by JohnnyQQQQ** [comment]
I don't think that this is an approach that scales very well. I would opt-in to go with a checkstyle on the changeset of every pull-request.

Ebay did a neat article on how this can be archieved https://ebaytech.berlin/checkstyle-on-changed-files-with-gradle-1619e49dbe4e

**Comment by jromero** [comment]
I think the scenarios are very different. They had a large code base to start off. This repo is still relatively small that all issues can be fixed fairly easily. The only reason why I didn't was to limit the changeset.

After all issues are fixed both solutions work about the same.

**Comment by AlmightyKerk** [comment]
Update  consistancy to consistency

**Comment by jromero** [comment]
> Update consistancy to consistency

Everyone's a critic... 😛

**Comment by sasaxie** [comment]
Dear developers:                                                                                                                                
Thank you for your enthusiasm and support to TRON. Recently we will make a standard form of submitting codes, so the new pull requests will not handled temporarily.

**Comment by jromero** [comment]
I've updated the PR an minimized the scope. I've also update the PR description to give a better understanding on what the changes are and what is still to come.

I've seen a lot of chatter in the gitter room about people wanting to help. Addressing lint warnings and setting the rule to error out in the future might be a good low hanging fruit for many.

**Pull request closed without merging**
