### PR TITLE
Fix permission in #93

### LINKED ISSUE #93: Compile error on the latest code in develop branch
1. What did you do?
I just synced and tried to build the project. 

2. What did you expect to see?
'BUILD SUCCESSFUL'

3. What did you see instead?
Bulild failed, here is the 1st compile error
_xxxxx/java-tron/src/main/java/org/tron/core/db/BlockStore.java:26: error: cannot find symbol
public class BlockStore extends **Database** {_

Commit 'Merge pull request #88 from ruchern/develop' is the latest good build

Please help to fix the compile error. Thanks!

### PR DESCRIPTION
**Pull request by ruchern**
Signed-off-by: Ru Chern Chong <me@ruchern.com>

**What does this PR do?**
Fix #93 where compiling is resulting in permission error.

**Why are these changes required?**
To fix the branch.

**This PR has been tested by:**
Gradle. Build successfully compiled.

screen shot 2018-02-01 at 2 21 31 am

### CODE REVIEW

**Comment by styk-tv** [comment]
https://github.com/tronprotocol/java-tron/issues/93 Can be closed now. Thanks @ruchern

**Comment by ruchern** [comment]
@sasaxie please kindly review and merge this. If other commits are being added right now, do inform me as I will have to rebase and fix any possible merge conflicts. DO NOT MERGE if this build failed.

**Comment by ybhgenius** [comment]
Hello, I am a crew member of TRON, and now we are planning to provide an incentive for your contribution. Please leave me your email address. Thanks.

**Comment by ruchern** [comment]
@ybhgenius prove that you're the crew member.

**Comment by ybhgenius** [comment]
Hello, my personal information has been updated in TRON's Github.

Please feel free to check the member list. Thanks a lot.

**Comment by ruchern** [comment]
@ybhgenius interesting but next to me please do not anyhow post like this. It completely look like a scam to me.

**Comment by ybhgenius** [comment]
Great, I totally understand that and your email please...

**Comment by ruchern** [comment]
@ybhgenius use my public email. me@ruchern.com

**Pull request merged**
