### PR TITLE
Enhance UtxoSet test coverage 

### PR DESCRIPTION
**Pull request by seanrobbins**
**What does this PR do?**

Increases the unit test coverage for UTXOSet so findSpendableOutputs and findUTXO are now covered.

**Why are these changes required?**

Looks like both important and complex functionality. The test hopefully enable changes to be made in this area with confidence and provide documentation on how UTXOSet works.

**This PR has been tested by:**
- Unit Tests

### CODE REVIEW

**Comment by jromero** [comment]
Minor: Can you use the google java format as defined on https://github.com/tronprotocol/java-tron/pull/60 ?

**Comment by seanrobbins** [comment]
Sure, I was kind of hoping #60 would get merged before this one so I could check against the lint task.

**Comment by seanrobbins** [comment]
Using this as my styleguide in IntelliJ from now on - https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml

**Comment by sasaxie** [comment]
Dear developers:                                                                                                                                Thank you for your enthusiasm and support to TRON. Recently we will make a standard form of submitting codes, so the new pull requests will not handled temporarily.

**Comment by seanrobbins** [comment]
The test failure on Travis is not related to the changes in this build, but the issue fixed in https://github.com/tronprotocol/java-tron/pull/74

**Comment by seanrobbins** [comment]
Closing as I believe the development on the project has moved on so fast, this PR is no longer relevant.

**Pull request closed without merging**
