### PR TITLE
feat: remove db after test

### PR DESCRIPTION
**Pull request by zhangwenhua-tron**
**What does this PR do?**
feat: remove db after test

**Why are these changes required?**

**This PR has been tested by:**
- Unit Tests
- Manual Testing

**Follow up**

**Extra details**

### CODE REVIEW

**Comment by WAT2519ty** [comment]
Thank. You.  
Khunanon. Wongouan
wiwatwongth@gmail.com

**Comment by WAT2519ty** [comment]
Khunanon. Wongouan
Thank.  You. Happy. To. Tread

**Comment by WAT2519ty** [comment]
Im. To. Tread. Free. Fun. Thank. You

**Review by WAT2519ty — COMMENTED** [review]
Thank. You. 
Very. Happy
Thank. You. Very. Mouht
Khunanon. Wongouan

**Comment by WAT2519ty** [comment]
Thank. You
Im. To. A. Happy.  

Khunanon. Wongouan

**Comment by WAT2519ty** [comment]
Thank. You
Im. To. A. Happy.  

Khunanon. Wongouan

**Comment by WAT2519ty** [comment]
Thank. You. Very. Moush. 

Khunano n. Wongouan

**Review by WAT2519ty — COMMENTED** [review]
Thank. You
Khunanon. Wongouan

wiwatwongth@gmail.com

**Review by WAT2519ty — COMMENTED** [review]
Tread. To.  Earn. Happy.  Thank. You
Khunanon. Wongouan
wiwatwongth@gmail.com

**Comment by WAT251922ty** [comment]
ในวันที่ พฤ. 23 ก.ย. 2021 11:23 WAT2519ty ***@***.***>
เขียนว่า:

**Comment by WAT251922ty** [comment]
Im. Noting.  A. Token. Pliesses

Zero. Token. By

Thank. You

Khunanon. Wongouan


You. Not. Send.  Gmail.

ในวันที่ พฤ. 23 ก.ย. 2021 11:01 wayne.zhang ***@***.***>
เขียนว่า:

**Review by Federico2014 — APPROVED** [review]

**Comment by WAT251922ty** [comment]
Fuk. You

Noting. A. Withd awal


Zero. Us. Noting. A. Withdrawal

Im. Dont. To. By.  Notebook

Fuk. You

Khunanon. Wongouan

ในวันที่ พ. 29 ก.ย. 2021 17:34 Federico2014 ***@***.***>
เขียนว่า:

**Pull request merged**
