### PR TITLE
owner 

### PR DESCRIPTION
**Pull request by Medomoha**
…l/src/mainsign update

**What does this PR do?**

**Why are these changes required?**

**This PR has been tested by:**
- Unit Tests
- Manual Testing

**Follow up**

**Extra details**

### CODE REVIEW

**Review by Medomoha — COMMENTED** [review]
good

**Review by Medomoha — COMMENTED** [review]
approved

**Comment by Medomoha** [comment]
1

**Comment by Medomoha** [comment]
.

**Comment by Medomoha** [comment]
approve

**Comment by Medomoha** [comment]
approve

**Comment by CABLESYALl** [comment]
Approve

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Medomoha** [comment]
done

**Pull request closed without merging**
