### PR TITLE
fix: change invalid if condition

### PR DESCRIPTION
**Pull request by AhnSinYong**
**What does this PR do?**
- change invalid if condition

**Why are these changes required?**
- "if condition" and "else if condition" are the same.

**This PR has been tested by:**
- Unit Tests
- Manual Testing

**Follow up**

**Extra details**

### CODE REVIEW

**Comment by AhnSinYong** [comment]
I do not know what the intention of the person who wrote this code is, so I can not give a concrete basis.
However, I wrote this PR because I think it will be possible to judge whether there is a problem when the code writer confirms it.

**Comment by AhnSinYong** [comment]
If it is an error, it will be a merge, otherwise the PR will just be closed.

**Comment by paulvi** [comment]
OK, so it is like questioning authors "hey, what is this for, is there error here?"

**Comment by Yrp** [comment]
@AhnSinYong @paulvi thank you for the help. We have fixed the issue. https://github.com/tronprotocol/java-tron/pull/645

**Pull request closed without merging**
