### PR TITLE
add db sync write

### PR DESCRIPTION
**Pull request by geb789**
**What does this PR do?**
add sync write and fix bug for update asset null
**Why are these changes required?**
add sync write and fix bug for update asset null

**This PR has been tested by:**
local

### CODE REVIEW

**Comment by jiangyy0824** [comment]
@geb789 Could you provide more detailed explanation of the update asset bug?

**Comment by geb789** [comment]
@jiangyy0824 
This pr solves two problems.
Firstly,  storage.db.sync parameter is invalid when flush function and create checkpoint function which can improve effective for update LEVELDB.
reference from: https://blog.csdn.net/acaiwlj/article/details/79509715.

**Comment by jiangyy0824** [comment]
@geb789 Thanks for your contribution. We will evaluate your PR ASAP.

**Comment by wubinTron** [comment]
good job

**Comment by zk19862018** [comment]
Hello,

Your PR has been merged into develop.
You earned 10 points.

You can track your points at:
https://tronscan.org/#/developersreward

**Pull request merged**
