### PR TITLE
test(LiteFullNode): add DbLiteTest test case

### PR DESCRIPTION
**Pull request by forfreeday**
**What does this PR do?**
1. add DbLiteTest test case
2. add test project dependencies: `framework`

**Why are these changes required?**
To improve test case execution efficiency and shorten test case execution time.

**This PR has been tested by:**
- Unit Tests
- Manual Testing

**Follow up**

**Extra details**

### CODE REVIEW

**Review by wubin01 — APPROVED** [review]

**Comment by chengtx01** [comment]
Please solve the following error:

> org.tron.plugins.DbLiteTest > testToolsWithLevelDBV2 FAILED
>        java.lang.RuntimeException: rename snapshot to output_lite_fn_LEVELDB_1690541222750/database failed
>        at org.tron.plugins.DbLiteTest.testTools(DbLiteTest.java:169)
>       at org.tron.plugins.DbLiteTest.testToolsWithLevelDBV2(DbLiteTest.java:111)

**Comment by forfreeday** [comment]
I'm checking this out.

**Comment by halibobo1205** [comment]
Is anyone working on this?

**Comment by halibobo1205** [comment]
@forfreeday Need to resolve coverage degradation.

**Comment by forfreeday** [comment]
@halibobo1205 
I agree with your suggestion.

**Pull request closed without merging**
