### PR TITLE
Add some unit test cases

### PR DESCRIPTION
**Pull request by vivian1912**
**What does this PR do?
Add some UT cases for VM/trace
Delete a duplicate UT file
**Why are these changes required?**
This folder has low code coverage rate
**This PR has been tested by:**
- Unit Tests
- Manual Testing

**Follow up**

**Extra details**
image

image

### CODE REVIEW

**Review by yanghang8612 — COMMENTED** [review]
LGTM

**Review by waynercheung — APPROVED** [review]
LGTM

**Review by Benson0224 — APPROVED** [review]
LGTM

**Review by jojo0770 — COMMENTED** [review]
Test

**Pull request merged**
