### PR TITLE
Revert "feat: add gettransactioninfobyblocknum, both fullNode and solidityNod…"

### PR DESCRIPTION
**Pull request by andelf**
Reverts tronprotocol/java-tron#2958

Reason:

The `tronprotocol/protocol` repo should be changed first.

Related: <https://github.com/tronprotocol/wallet-cli/pull/342>

The better solution is switching to git submodule.

### CODE REVIEW

**Comment by ruchern** [comment]
# [Codecov](https://codecov.io/gh/tronprotocol/java-tron/pull/2961?src=pr&el=h1) Report
> Merging [#2961](https://codecov.io/gh/tronprotocol/java-tron/pull/2961?src=pr&el=desc) into [release_4.1](https://codecov.io/gh/tronprotocol/java-tron/commit/f9c72f87d165f27c61f9b2067a1e8096ed4aff4f&el=desc) will **decrease** coverage by `0.56%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/tronprotocol/java-tron/pull/2961?src=pr&el=tree)

```diff
@@                Coverage Diff                @@
##             release_4.1    #2961      +/-   ##
=================================================
- Coverage          31.47%   30.91%   -0.57%     
+ Complexity          1963     1912      -51     
=================================================
  Files                386      384       -2     
  Lines              19427    19326     -101     
  Branches            2237     2228       -9     
=================================================
- Hits                6115     5974     -141     
- Misses             12589    12655      +66     
+ Partials             723      697      -26     
```


| [Impacted Files](https://codecov.io/gh/tronprotocol/java-tron/pull/2961?src=pr&el=tree) | Coverage Δ | Complexity Δ | |
|---|---|---|---|
| [...n/common/net/udp/message/discover/PongMessage.java](https://codecov.io/gh/tronprotocol/java-tron/pull/2961/diff?src=pr&el=tree#diff-ZnJhbWV3b3JrL3NyYy9tYWluL2phdmEvb3JnL3Ryb24vY29tbW9uL25ldC91ZHAvbWVzc2FnZS9kaXNjb3Zlci9Qb25nTWVzc2FnZS5qYXZh) | `0.00% <0.00%> (-90.00%)` | `0.00% <0.00%> (-4.00%)` | |
| [...org/tron/common/net/udp/handler/PacketDecoder.java](https://codecov.io/gh/tronprotocol/java-tron/pull/2961/diff?src=pr&el=tree#diff-ZnJhbWV3b3JrL3NyYy9tYWluL2phdmEvb3JnL3Ryb24vY29tbW9uL25ldC91ZHAvaGFuZGxlci9QYWNrZXREZWNvZGVyLmphdmE=) | `11.76% <0.00%> (-47.06%)` | `2.00% <0.00%> (-1.00%)` | |
| [.../tron/common/overlay/discover/table/NodeEntry.java](https://codecov.io/gh/tronprotocol/java-tron/pull/2961/diff?src=pr&el=tree#diff-ZnJhbWV3b3JrL3NyYy9tYWluL2phdmEvb3JnL3Ryb24vY29tbW9uL292ZXJsYXkvZGlzY292ZXIvdGFibGUvTm9kZUVudHJ5LmphdmE=) | `0.00% <0.00%> (-46.52%)` | `0.00% <0.00%> (-7.00%)` | |
| [.../java/org/tron/common/net/udp/message/Message.java](https://codecov.io/gh/tronprotocol/java-tron/pull/2961/diff?src=pr&el=tree#diff-ZnJhbWV3b3JrL3NyYy9tYWluL2phdmEvb3JnL3Ryb24vY29tbW9uL25ldC91ZHAvbWVzc2FnZS9NZXNzYWdlLmphdmE=) | `26.08% <0.00%> (-30.44%)` | `3.00% <0.00%> (-3.00%)` | |
| [...rg/tron/common/net/udp/handler/MessageHandler.java](https://codecov.io/gh/tronprotocol/java-tron/pull/2961/diff?src=pr&el=tree#diff-ZnJhbWV3b3JrL3NyYy9tYWluL2phdmEvb3JnL3Ryb24vY29tbW9uL25ldC91ZHAvaGFuZGxlci9NZXNzYWdlSGFuZGxlci5qYXZh) | `72.41% <0.00%> (-27.59%)` | `6.00% <0.00%> (-2.00%)` | |
| [...n/common/net/udp/message/discover/PingMessage.java](https://codecov.io/gh/tronprotocol/java-tron/pull/2961/diff?src=pr&el=tree#diff-ZnJhbWV3b3JrL3NyYy9tYWluL2phdmEvb3JnL3Ryb24vY29tbW9uL25ldC91ZHAvbWVzc2FnZS9kaXNjb3Zlci9QaW5nTWVzc2FnZS5qYXZh) | `63.33% <0.00%> (-20.01%)` | `1.00% <0.00%> (-4.00%)` | |
| [...tron/common/overlay/discover/node/NodeHandler.java](https://codecov.io/gh/tronprotocol/java-tron/pull/2961/diff?src=pr&el=tree#diff-ZnJhbWV3b3JrL3NyYy9tYWluL2phdmEvb3JnL3Ryb24vY29tbW9uL292ZXJsYXkvZGlzY292ZXIvbm9kZS9Ob2RlSGFuZGxlci5qYXZh) | `33.87% <0.00%> (-17.75%)` | `10.00% <0.00%> (-8.00%)` | |
| [.../tron/common/overlay/discover/table/NodeTable.java](https://codecov.io/gh/tronprotocol/java-tron/pull/2961/diff?src=pr&el=tree#diff-ZnJhbWV3b3JrL3NyYy9tYWluL2phdmEvb3JnL3Ryb24vY29tbW9uL292ZXJsYXkvZGlzY292ZXIvdGFibGUvTm9kZVRhYmxlLmphdmE=) | `26.15% <0.00%> (-12.31%)` | `7.00% <0.00%> (-4.00%)` | |
| [...va/org/tron/common/overlay/discover/node/Node.java](https://codecov.io/gh/tronprotocol/java-tron/pull/2961/diff?src=pr&el=tree#diff-ZnJhbWV3b3JrL3NyYy9tYWluL2phdmEvb3JnL3Ryb24vY29tbW9uL292ZXJsYXkvZGlzY292ZXIvbm9kZS9Ob2RlLmphdmE=) | `47.29% <0.00%> (-12.17%)` | `10.00% <0.00%> (-6.00%)` | |
| [...tron/common/overlay/discover/node/NodeManager.java](https://codecov.io/gh/tronprotocol/java-tron/pull/2961/diff?src=pr&el=tree#diff-ZnJhbWV3b3JrL3NyYy9tYWluL2phdmEvb3JnL3Ryb24vY29tbW9uL292ZXJsYXkvZGlzY292ZXIvbm9kZS9Ob2RlTWFuYWdlci5qYXZh) | `50.40% <0.00%> (-11.21%)` | `20.00% <0.00%> (-3.00%)` | |
| ... and [6 more](https://codecov.io/gh/tronprotocol/java-tron/pull/2961/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/tronprotocol/java-tron/pull/2961?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/tronprotocol/java-tron/pull/2961?src=pr&el=footer). Last update [f9c72f8...0018590](https://codecov.io/gh/tronprotocol/java-tron/pull/2961?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by andelf** [comment]
@zhangwenhua-tron 
Haven't seen your PR on https://github.com/tronprotocol/protocol, will reopen.

**Comment by andelf** [comment]
re-open for not fixed yet.

**Comment by jiangyy0824** [comment]
Other devs will also change the repo, and we plan to complete the modifications uniformly before release. So close the revert PR. Thanks.

**Pull request closed without merging**
